import './globals.css'
import type { Metadata } from 'next'
import Navbar from './layout/Navbar/Navbar'
import Footer from './layout/Footer/Footer'



export const metadata: Metadata = {
  title: 'Real Estate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Navbar/>{children}
      <Footer/>
      </body>
    </html>
  )
}
